### ISSUE TITLE
角色权限修改问题

### ISSUE THREAD

**Issue by echoopen** [insistence/Dash-FastAPI-Admin#4]
角色管理如果先设置了某个菜单权限，然后在菜单管理里面关闭这个菜单功能，会导致角色权限不能修改

![image](https://github.com/insistence/Dash-FastAPI-Admin/assets/62507651/dec8e1a7-c365-4363-92ad-fb78a38f15c5)

![image](https://github.com/insistence/Dash-FastAPI-Admin/assets/62507651/36dd7b44-e696-4def-9b4f-2700f226111d)

menu的列表里面出现了null，然后代码就不会运行了。

**Comment by insistence** [comment]
感谢反馈，已修复
